<a href="https://colab.research.google.com/github/junsu122/AI_Basic/blob/main/Tensor_%EC%9D%B4%EB%A1%A0/%EA%B8%B0%EB%B3%B8_%ED%85%90%EC%84%9C(Tensor).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 텐서(Tensor)
## 2.1 텐서(Tensor) 소개


- 최근의 머신 러닝 시스템은 일반적으로 **텐서를 기본 데이터 구조**로 사용한다.  
- 데이터를 위한 컨테이너라고 생각하면 쉽게 이해할 수 있다.
- NumPy는 훌륭한 프레임워크지만, GPU를 사용하여 수치 연산을 가속화할 수는 없기 때문에 GPU연산이 가능한 PyTorch에서의 Tensor를 사용한다. (디바이스 선택이 수월함.)


  심층 신경망에서 GPU는 종종 50배 또는 그 이상의 속도 향상을 제공하기 때문에, 안타깝게도 NumPy는 딥러닝 프로그래밍에는 충분치 않다.


- **PyTorch 텐서(Tensor)는 개념적으로 NumPy 배열과 동일** : 텐서(Tensor)는 n-차원 배열이며, PyTorch는 이러한 텐서들의 연산을 위한 다양한 기능들을 제공한다.


> ### 텐서의 특성


-   축의 개수:  
    랭크(Rank)라고도 부르며, 넘파이 배열에서는 `ndim`을 통해 확인할 수 있다.  
   
-   크기:  
    텐서의 각 축을 따라 얼마나 많은 차원이 있는지를 나타낸 튜플 넘파이 배열에서는 `shape`을 통해 확인할 수 있다.  


-   데이터 타입:  
    텐서에 포함된 데이터 타입이다.  
    타입은 float32, unit8, float64 등이 될 수 있으며 문자열은 지원하지 않는다. `dtpye` 속성으로 데이터를 확인할 수 있다.


In [ ]:
# 스칼라 (0 D Tensor)
# 하나의 숫자만을 담고 있은 텐서 (0차원 텐서)
# 스칼라의 축의 개수 : 0개

import torch
import numpy as np

np.array(10)
scalar = np.array(10)
print(scalar)
print(scalar.ndim)
print(scalar.shape)
# () : 차원이 없으므로 빈 튜플이 출력

10
0
()


In [ ]:
# 벡터 (Vector) (1 D Tensor)
# 숫자의 배열을 벡터, 1차원 텐서
# 벡터의 축의 개수 : 1개

vector = np.array([1,2,3,4,5])
print(vector)
print(vector.ndim) # 차원
print(vector.shape) # 배열의 크기

[1 2 3 4 5]
1
(5,)


In [ ]:
# 행렬(Matrix) (2 D Tensor)
# 벡터의 배열을 행렬, 2차원 텐서
# 행렬은 행, 열 2가지 축이 있음

matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [ ]:
# 고차원 텐서
# 행렬들을 하나의 새로운 배열로 합치면 숫자로 채워진 직육면체가 된다. (3 D Tensor)
# 딥러닝에서는 보통 5차원 텐서까지 다룸

np.arange(24)
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
tensor_3d = np.arange(24).reshape(2,3,4)

print(tensor_3d)
# 2개의 3*4 행렬 구성
print(tensor_3d.ndim) # 차원수 : 3개
print(tensor_3d.shape) # 텐서 형태는 2개의 3*4 크기 행렬 포함

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3
(2, 3, 4)


 ### Tensor의 Shape
넘파이의 배열에서 `shape`를 이용하여 텐서의 크기를 알아볼 경우 return값은 다음과 같다  

**1차원 : (열,)**  
**2차원 : (행, 열)**  
**3차원 : (깊이, 행, 열)**  

즉, 열의 기준이 되어 차원이 늘어날수록 늘어난 차원의 크기가 열의 앞에 추가된다고 생각하면 된다.  
머신러닝에서 사용하는 train\_data의 shape은 다음과 같다.  


**1\. 벡터 데이터: (samples, features) 2D tensor**
집값 예측 문제라고 생각하고 주어진 데이터가 100개의 연식, 동네, 역세권의 유무에 따른 데이터라고 하면 (100, 3)크기의 텐서에 저장될 수 있다.  


**2\. 이미지: (samples, height, width, channels) 4D tensor**
채널 우선방식 과 채널 마지막 방식 으로 나뉘지만 보통의 경우 100 장의 28x28의 컬러 이미지라면 (100, 28, 28, 3)크기의 텐서에 저장될 수 있다.  


**3\. 동영상: (samples, Time(frames), height, width, channels) 5D tensor**

FPS(Frame per Second)




In [ ]:
import numpy as np
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
print(train_images.shape)
# (60000, 28, 28) 28*28 image가 60000장
print(test_images.shape)

(60000, 28, 28)
(10000, 28, 28)


In [ ]:
use_images = train_images[:100,:,:]
print(use_images.shape)

(100, 28, 28)


In [ ]:
# 여기서 질문
# 6만장의 데이터 중 위쪽 절반만 사용하고 싶다면?
train_images[:,:14,:].shape

(60000, 14, 28)

#### ※ Tensor과 Ndarray
- 텐서 (Tensor)는 NumPy 어레이와 비슷하지만, 텐서는 GPU, TPU와 같은 가속기에서 사용할 수 있고, 텐서는 값을 변경할 수 없습니다.




먼저 Pytorch에서 주로 다루는 데이터 자료형인 Tensor과 Numpy에서 주로 다루는 데이터 자료형인 ndarray는 다차원 배열과 배열 생성 시 다양한 데이터 타입 적용이 가능하지만 주요한 차이점이 존재합니다.


우선 가장 중요한 차이점은 GPU를 활용한 연산이 가능한가? 이며, 그 외로 중요한 기능들에서 차이점이 있습니다


## Tensor 생성하기

- 텐서는 파이토치에서 스칼라, 벡터, 행렬 같은 개념으로 연산에 사용하는 기본적인 자료구조이며 다차원 배열로 표현할 수 있습니다.
- 파이썬 numpy의 ndarray와 유사합니다.(n차원의 배열 객체)
- 텐서는 n차원으로 구성되어 있는데 0차원은 스칼라, 1차원은 벡터, 2차원은 행렬, 3차원부터 텐서입니다.
- 1차원 텐서, 2차원 텐서, 3차원 텐서라고도 합니다.
- torch 패키지를 임포트하고 tensor 함수를 이용하여 텐서를 생성할 수 있습니다.


In [ ]:
import torch

a = torch.tensor([1,2,3,4,5])
print(a)

print('텐서크기',a.size())

tensor([1, 2, 3, 4, 5])
텐서크기 torch.Size([5])


In [ ]:
# 2차원 텐서 생성

x1 = torch.tensor([[1,2,3]
                  ,[4,5,6]
                   ,[7,8,9]])

print(x1)
print(x1.size())
print(x1.dim()) # 차원

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])
2


In [ ]:
# 3행 2열 리스트로 2차원 텐서 생성

data = [[1,2],[4,5],[6,7]]
data

[[1, 2], [4, 5], [6, 7]]

In [ ]:
torch.tensor(data)

tensor([[1, 2],
        [4, 5],
        [6, 7]])

In [ ]:
x2 = torch.tensor(data)
print(x2)
print(x2.shape)

tensor([[1, 2],
        [4, 5],
        [6, 7]])
torch.Size([3, 2])


In [ ]:
# 3차원 텐서 생성

x3 = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(x3)
print('텐서크기 :',x3.size())

# 1개의 2차원 행렬(3*3)
# 첫번째 차원(깊이) 크기 : 1
# 두번째 차원(행) 크기 : 3
# 세번째 차원(열) 크기 : 3

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
텐서크기 : torch.Size([1, 3, 3])


In [ ]:
# 넘파이 배열과 파이토치 텐서간 변환

import torch
import numpy as np

x4 = [[1,2,3],[4,5,6],[7,8,9]]
x4

np.array(x4)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# 특정값으로 텐서 생성

In [ ]:
import torch

torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.full((2,3),7)

tensor([[7, 7, 7],
        [7, 7, 7]])

random 한 텐서 생성

In [ ]:
import torch

# 정규분포를 따르는 무작위한 텐서 생성
torch.randn((2,3))

tensor([[ 1.0897, -1.7109, -0.7933],
        [ 0.2169,  1.4039,  0.2330]])

In [ ]:
random_tensor = torch.randn((2,3))
random_tensor

tensor([[-2.0231,  0.0438, -0.3024],
        [-0.3010, -1.2775, -1.7042]])

In [ ]:
# rand_like = 형태를 똑같게 함.
torch.rand_like(random_tensor)

tensor([[0.3065, 0.8600, 0.1872],
        [0.7588, 0.5034, 0.7321]])

In [ ]:
import torch

# rand(행,열) 0-1 사이의 실수값으로 채워진 텐서
tensor_random = torch.rand(2,3)

print(tensor_random)
#

tensor([[0.9628, 0.4336, 0.7043],
        [0.1914, 0.5172, 0.2268]])


In [ ]:
torch.arange(1,7).reshape(2,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
tensor_arange = torch.arange(1,7).reshape(2,3)
tensor_arange

tensor([[1, 2, 3],
        [4, 5, 6]])

텐서 속성


- 텐서의 차원을 확인하는 dim() 메서드가 있습니다. 이는 텐서의 rank라고도 불립니다.
- 텐서의 형상(shape)을 확인하는 shape 속성이 있습니다. 이는 각 차원의 크기를 튜플 형태로 반환합니다.
- 텐서의 크기를 확인하는 size() 메서드도 있습니다. 이는 shape와 동일한 정보를 반환합니다.
- 데이터타입 자료형을 확인하는 dtype 속성은 datatype() 속성이며, 이를 통해 텐서의 데이터 타입(예: 정수, 실수, 불리언 등)을 알 수 있습니다.
- 텐서가 저장된 장치(CPU 또는 GPU)를 확인하는 device 속성이 있습니다.
- 텐서의 총 원소 개수를 반환하는 numel() 메서드도 유용합니다.


In [ ]:
import torch

x = torch.randn(3,4,5)
# 3*4*5 크기의 3차원 텐서 생성
print(x)
print(x.dim())
print(x.shape)
print(x.size())
print(x.dtype)
print(x.device)
print(x.numel()) # 텐서의 총 원소 개수 반환(numel: number of element)

tensor([[[ 1.3770, -0.1689,  1.4882,  1.0918, -0.1983],
         [ 0.3816, -1.3599, -0.1747,  0.3775,  1.1640],
         [ 1.5977,  0.3330,  0.9962,  0.4081, -1.2405],
         [ 0.4907,  0.3027, -0.2174,  0.5762,  0.9778]],

        [[-0.7476, -0.0505,  1.1805, -0.2343, -0.6663],
         [-0.3270,  0.5587, -0.2389, -1.3632, -0.2684],
         [-1.0926,  0.9120, -1.5132, -0.9330, -1.2846],
         [-0.2894,  0.8764, -0.3388, -0.2128, -0.5950]],

        [[-0.6405,  0.8402, -0.3993, -1.4032,  0.3617],
         [-1.1487,  0.9324, -0.2827,  1.8321,  0.2133],
         [ 1.9032,  0.4736, -0.3560,  0.6266, -0.2346],
         [ 0.1367, -2.2636, -0.8571, -0.7713,  1.2418]]])
3
torch.Size([3, 4, 5])
torch.Size([3, 4, 5])
torch.float32
cpu
60


In [ ]:
import torch

# 1차원 텐서
a = torch.tensor([1,2,3,4,5])
print(a.size())

torch.Size([5])


In [ ]:
print(a.shape)

torch.Size([5])


In [ ]:
print(a.dim())

1


In [ ]:
print(a.ndimension())

1


In [ ]:
print(a.dtype)

torch.int64


In [ ]:
# 2차원 텐서
import torch

torch.FloatTensor([[1,2],[3,4]])

tensor([[1., 2.],
        [3., 4.]])

In [ ]:
x4 = torch.FloatTensor([[1,2],[3,4]])
x4.size()

torch.Size([2, 2])

In [ ]:
x4.shape


torch.Size([2, 2])

In [ ]:
x4.dim()


2

In [ ]:
x4.ndimension()


2

In [ ]:
x4.dtype

torch.float32

In [ ]:
# 3차원 텐서
import torch

torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x5 = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
x5.shape

torch.Size([1, 3, 3])

In [ ]:
x5.dim()

3

In [ ]:
x5.ndimension()

3

In [ ]:
x5.dtype

torch.int64

텐서 생성
- 행렬 곱셈 기본 원리
- 첫번째 행렬 열수와 두번째 행렬의 행수가 일치해야 행렬 곱셈 가능

In [ ]:
import torch

# [2,3]과 [3,2] 텐서 생성
a = torch.tensor([[1,2,3],[4,5,6]])
b = torch.tensor([[7,8],[9,10],[11,12]])

torch.matmul(a,b)
# matmul(a,b) a와 b 행렬 곱셈(내적) : matrix mulplication

tensor([[ 58,  64],
        [139, 154]])

In [ ]:
c = torch.matmul(a,b)
print(c.shape)

torch.Size([2, 2])


In [ ]:
import torch

tensor1 = torch.tensor([1,2,3])
tensor2 = torch.zeros(3,3)
tensor3 = torch.ones(2,2)
tensor4 = torch.rand(3,3)

# tensor 조작
reshaped = tensor4.reshape(1,9)
transposed = tensor4.t()

print("original:",tensor4)
print("reshaped:",reshaped)
print("transposed:",transposed)

original: tensor([[0.7997, 0.0271, 0.7188],
        [0.9351, 0.7248, 0.8737],
        [0.4381, 0.5595, 0.2580]])
reshaped: tensor([[0.7997, 0.0271, 0.7188, 0.9351, 0.7248, 0.8737, 0.4381, 0.5595, 0.2580]])
transposed: tensor([[0.7997, 0.9351, 0.4381],
        [0.0271, 0.7248, 0.5595],
        [0.7188, 0.8737, 0.2580]])


In [ ]:
# 실수형과 정수형 텐서 생성

import torch

torch.tensor([1.5,2.5,3.5],dtype=torch.float32)

tensor([1.5000, 2.5000, 3.5000])

In [ ]:
float_tensor = torch.tensor([1.5,2.5,3.5],dtype=torch.float32)
float_tensor

tensor([1.5000, 2.5000, 3.5000])

In [ ]:
torch.tensor([1,2,3],dtype=torch.int64)

tensor([1, 2, 3])

텐서 연산

#### 기본 연산


-   **덧셈과 뺄셈**: 같은 크기의 텐서 간에 요소별로 수행됩니다.
-   **요소별 곱셈**: 두 텐서의 대응하는 요소끼리 곱합니다.
-   **스칼라 곱**: 텐서의 모든 요소에 스칼라 값을 곱합니다.


#### 행렬 곱셈


-   행렬 곱셈은 `torch.matmul()` 또는 `@` 연산자를 사용합니다.
-   왼쪽 행렬의 열 수와 오른쪽 행렬의 행 수가 일치해야 합니다.
-   결과 행렬의 크기는 (왼쪽 행렬의 행 수) x (오른쪽 행렬의 열 수)가 됩니다.


#### 고급 연산


-   **전치(Transpose)**: 행과 열을 바꾸는 연산으로, `t()` 메서드를 사용합니다.
-   **차원 축소**: `sum()`, `mean()` 등의 함수로 특정 차원을 따라 값을 집계합니다.
-   **브로드캐스팅**: 크기가 다른 텐서 간의 연산을 자동으로 조정합니다.


#### 비선형 활성화 함수


-   ReLU, Sigmoid, Tanh 등의 함수를 텐서에 적용하여 비선형성을 도입합니다.


이러한 연산들은 신경망의 순전파와 역전파 과정에서 핵심적인 역할을 합니다.


효율적인 텐서 연산은 딥러닝 모델의 성능과 학습 속도에 직접적인 영향을 미칩니다.


In [ ]:
import torch
import numpy as np

# 1차 텐서 덧셈
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

c = a+b
print(c)
print(c.shape)

tensor([5, 7, 9])
torch.Size([3])


In [ ]:
c = a - b
print(c)
print(c.shape)

tensor([-3, -3, -3])
torch.Size([3])


In [ ]:
# 기본 연산
addition = a+b
muliplication = a*b
dot_product = torch.dot(a,b)

In [ ]:
print(addition)
print(muliplication)
print(dot_product)

tensor([5, 7, 9])
tensor([ 4, 10, 18])
tensor(32)


In [ ]:
import torch

device = torch.device('cuda' if torch.cuda.is_available()else "cpu")
tensor = torch.rand(3,3).to(device)
print(f'Tensor is on {device}')

Tensor is on cpu


텐서 곱셈

In [ ]:
# 행렬 곱 matmul 주의할 점
# >> 행렬 a의 열의 수와 b의 행의 수가 같아야 함

In [ ]:
import torch
import numpy as np

a = torch.tensor([10,20,30])
b = torch.tensor([2,4,5])

result = a/b
result2 = torch.div(a,b)
result2

tensor([5., 5., 6.])

In [ ]:
a

tensor([10, 20, 30])

In [ ]:
result3 = a**2
result4 = torch.pow(a,2)
result4

tensor([100, 400, 900])

In [ ]:
tensor = torch.tensor([[1,2,3],[4,5,6]])

# 전체 합계 1+2+3...+6 =21
torch.sum(tensor)

tensor(21)

In [ ]:
tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# 특정 차원의 합계 // 행 기준으로 열의 합 = 위 아래로 더한값
torch.sum(tensor, dim=0)
# 행 기준, 열의 합

tensor([5, 7, 9])

In [ ]:
torch.sum(tensor, dim=1)
# 열 기준, 행의 합

tensor([ 6, 15])

In [ ]:
# 최대값
torch.max(tensor)


tensor(6)

In [ ]:
# 최소값
torch.min(tensor)

tensor(1)

In [ ]:
# 3보다 큰 값들만 True
result = tensor > 3
result

tensor([[False, False, False],
        [ True,  True,  True]])

텐서 연산을 위한 텐서 변환
 - 차원 변경
 - view(), unsqueeze(), squeeze()
 - 매우 중요한 것은 차원 크기가 무조건 1로 늘어나거나 1인 것만 줄일 수 있다.

In [ ]:
import torch

exam = torch.rand(3,1,4,1)
print(exam.shape)
print(exam.dim())

torch.Size([3, 1, 4, 1])
4


In [ ]:
# torch.Size([3,1,4,1])
# 3,1,4,1 차원의 idx(index) 0,1,2,3

exam = exam.squeeze(dim=1) # squeeze = 선택한 인덱스의 차원 줄이기(1이여야함)
print(exam.shape)
print(exam.dim())

torch.Size([3, 4, 1])
3


In [ ]:
exam = exam.squeeze(dim=1) # 선택한 인덱스가 1이 아니기 때문에 변동없음.
print(exam.shape)
print(exam.dim())

torch.Size([3, 4, 1])
3


In [ ]:
exam = exam.squeeze(dim=-1)
print(exam.shape)
print(exam.dim()) # 변동있음

torch.Size([3, 4])
2


In [ ]:
exam = exam.unsqueeze(dim=0)
print(exam.shape)
print(exam.dim())

torch.Size([1, 3, 4])
3


In [ ]:
exam = exam.unsqueeze(dim=-1)
print(exam.shape)
print(exam.dim())

torch.Size([1, 3, 4, 1])
4


- 차원 확장하거나 축소, unsqueeze, squeeze
- tensor 확장은 무조건 차원 확장 후, 차원값 확장으로 진행됨
- 확장했으면 확장된 차원크기 조정하는 메서드 알아보자구요

In [ ]:
# torch.repeat(), torch.expand()

# 정수 데이터 타입으로 난수 생성
torch.randint(0,4,(3,2))

tensor([[1, 3],
        [3, 3],
        [0, 2]])

In [ ]:
original = torch.randint(0,4,(3,2))

# 차원 확장 [3,2] >> [1,3,2]
original.unsqueeze(0)

tensor([[[3, 1],
         [3, 1],
         [2, 2]]])

In [ ]:
temp = original.unsqueeze(0)

# 확장된 차원을 반복해서 늘리고 싶어라 [1,3,2] >> [4,3,2]
# size=1인 차원만 확장 가능
# expand = view * broadcasting
temp.expand(4,3,2)

tensor([[[3, 1],
         [3, 1],
         [2, 2]],

        [[3, 1],
         [3, 1],
         [2, 2]],

        [[3, 1],
         [3, 1],
         [2, 2]],

        [[3, 1],
         [3, 1],
         [2, 2]]])

In [ ]:
temp.expand(4,3,2).shape

torch.Size([4, 3, 2])

In [ ]:
temp

tensor([[[3, 1],
         [3, 1],
         [2, 2]]])

In [ ]:
temp.size()

torch.Size([1, 3, 2])

In [ ]:
# 확장된 차원을 repeat 메서드 늘림
temp.repeat(4,1,1)
# repeat(dim=0,dim=1,dim=2)
# dim=0  4로 설정 : 첫번째 차원 4번 복제
# dim=1 , dim=2 로 설정 : 처음과 그대로 유지

tensor([[[3, 1],
         [3, 1],
         [2, 2]],

        [[3, 1],
         [3, 1],
         [2, 2]],

        [[3, 1],
         [3, 1],
         [2, 2]],

        [[3, 1],
         [3, 1],
         [2, 2]]])

`expand`는 차원 사이즈가 늘어나도 메모리는 공유되고 있기에  
하나의 원소값을 변조하면 공유 메모리로 묶여있는 다른 원소도 같이 영향받는다.


따라서 `expand`로 차원을 늘리는 경우는 브로드 캐스팅 방식으로 읽기전용 데이터를 만들 때 최적화 측면에서 사용하는 메서드라 보면 된다.


반대로 `repeat`메서드는 차원사이즈가 늘어나면 복제된 데이터는 완전히 독립적으로 운용되어 원소 변조가 발생하는 쓰기데이터일 때 위 메서드를 사용한다.

> ### 주요 텐서 변환 함수


#### view() 함수


-   텐서의 크기를 변경하는 데 사용됩니다.
-   변경 후에도 텐서 원소의 총 개수는 동일해야 합니다.
-   예: `x1_tensor = x_tensor.view(2, 3)`는 3x2 텐서를 2x3 텐서로 변환합니다.


#### unsqueeze() 함수


-   지정된 위치에 새로운 차원을 추가합니다.
-   `dim` 매개변수로 차원을 추가할 위치를 지정합니다.
-   예: `uns_tensor = x_tensor.unsqueeze(0)`는 첫 번째 위치에 새 차원을 추가합니다.


#### squeeze() 함수


-   크기가 1인 차원을 제거합니다.
-   특정 연산 후 불필요한 차원을 제거할 때 유용합니다.
-   예: `s_tensor = uns_tensor.squeeze()`는 크기가 1인 모든 차원을 제거합니다.


> ### 추가적인 텐서 변환 기능


#### chunk() 함수


-   텐서를 지정된 수의 덩어리로 나눕니다.
-   예: `chunks = torch.chunk(tensor, 3)`는 텐서를 3개의 덩어리로 나눕니다.


#### split() 함수


-   텐서를 지정된 크기의 덩어리로 나눕니다.
-   예: `splits = torch.split(tensor, 2)`는 텐서를 2개의 원소를 가진 덩어리들로 나눕니다.


이러한 텐서 변환 함수들은 딥러닝 모델 구축 및 데이터 전처리 과정에서 매우 유용하게 사용됩니다.


특히 복잡한 신경망 구조에서 텐서의 형태를 조정하거나, 배치 처리를 위해 데이터의 차원을 조정할 때 자주 활용됩니다.
